### PR TITLE
Created a .NET 5.0 project

### PR DESCRIPTION
**Pull request by prayaas-a**
This PR adds a .NET 5.0 winforms project to the solution that'll be super helpful in comparing performance across frameworks. The actual code is as true as possible to the original .NET Framework 4.6 project and I have configured the project configuration to be similar as well.
No changes to the original project.
Testing notes:
Unexpectedly, the .NET 5.0 version is slightly slower in my informal tests (the 5.0 runtime otherwise has a lot of performance improvements). Also, some breaking change was made by the WinForms team, so the window size specified in the original version is now bigger than what the controls take up.

### CODE REVIEW

**Comment by ADeltaX** [comment]
> Also, some breaking change was made by the WinForms team, so the window size specified in the original version is now bigger than what the controls take up.

This is referring to a dpi of more than 100%? Because if I set the same window size in both netfx 4.6 and .net 5 I get the same window size at runtime, at least with 100% dpi.
image

**Comment by prayaas-a** [comment]
> > Also, some breaking change was made by the WinForms team, so the window size specified in the original version is now bigger than what the controls take up.
> 
> This is referring to a dpi of more than 100%? Because if I set the same window size in both netfx 4.6 and .net 5 I get the same window size at runtime, at least with 100% dpi.

Yes, this is on a Surface Book (3000x2000) at 200% dpi:

image

That makes me think this might be a bug in the .NET (Core) version of winforms. I'll try to repro separately later and file an issue with them. Glad it works 1-to-1 on 100% dpi though!

Btw, looks like a slight performance degradation on .NET 5 is the recurring theme here. I'd guess it's because .NET FX hooks into the OS much more directly than .NET does/can and thus has a performance benefit (less wrapping, less context switching possibly).

**Comment by ADeltaX** [comment]
Actually in my case the .NET 5 version is considerably faster at generating controls compared to .NET Framework 4.6 in every version **except 19041+**. I run this multiple times.
Redraw speed is both the same for netfx and netcore.

(Both compiled in Release, .NET 5 is self-contained, single file and trimmed)

> 15063
image

> 16299
image

> 17134
image

> 17763
image

> 18362 [what a huge difference here]
image

> 19041 [here netfx beats netcore]
image

**Comment by ADeltaX** [comment]
I'll merge it and add an additional fix for the sizing problem

**Pull request merged**
